version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./numeri.db
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/numeri.db:/app/numeri.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api

volumes:
  db_data: